version: "3.2"
services:
  pub:
    build: ./pub
    networks:
      inner_net:
        aliases:
          - pub

  sub:
    build: ./sub
    # command: "pub:5556"
    networks:
      inner_net:
        aliases:
          - sub

networks:
  inner_net:
